# Copyright (c) 2008-2009 IBM Corp. and Others. All Rights Reserved

# local definitions can go in Makefile.local
# example:

## debug options
EXTRA_COMPILE_OPTS=-g

## configure options
#EXTRA_CONFIGURE_OPTS=--with-library-suffix=srl

