#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:49 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.bnf

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/BigNumberFormatTest.java			\


include $(TOPDIR)/src/build/rules.gmk