#!/bin/sh
## -*-sh-*-
#set -x
# BEGIN of icu-config-top
#******************************************************************************
#   Copyright (C) 2016 and later: Unicode, Inc. and others.
#   License & terms of use: http://www.unicode.org/copyright.html
#******************************************************************************
# This script is designed to aid configuration of ICU.
# rpath links a library search path right into the binaries.
#
# Note: it's preferred to use the .pc files rather than icu-config.
#

### END of icu-config-top

## Zero out prefix.
execprefix=
prefix=


loaddefs()
{

