#
# $RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/25 18:27:21 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.topleveltest

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/TestAll.java   \


!include $(TOPDIR)/src/build/rules.mak
