# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /icu4j
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /tools/cldr/cldr-to-icu
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /tools/release/java
    schedule:
      interval: daily
