#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:43 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.demo.holiday

include $(TOPDIR)/src/build/defs.gmk

FILES_java=	$(TARGDIR)/HolidayBorderPanel.java	\
			$(TARGDIR)/HolidayCalendarDemo.java	\

include $(TOPDIR)/src/build/rules.gmk
