#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:44 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.demo.holiday

!include $(TOPDIR)/src/build/defs.mak

FILES_java=	$(TARGDIR)/HolidayBorderPanel.java	\
			$(TARGDIR)/HolidayCalendarDemo.java	\

!include $(TOPDIR)/src/build/rules.mak
