#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:54 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.rbnf

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/RbnfTest.java			\
			$(TARGDIR)/RbnfRoundTripTest.java	\


!include $(TOPDIR)/src/build/rules.mak
