#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:45 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.demo.rbnf

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/RbnfDemo.java			\
			$(TARGDIR)/RbnfSampleRuleSets.java	\


!include $(TOPDIR)/src/build/rules.mak
