#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:36 $
#

TOPDIR=		../../..
PACKAGE=	com.ibm

include $(TOPDIR)/src/build/defs.gmk

SUBDIRS=	util text

include $(TOPDIR)/src/build/rules.gmk

