#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:08 $
#

TOPDIR=		../../../..
PACKAGE=	com.ibm.util
SUBDIRS=	resources

include $(TOPDIR)/src/build/defs.gmk

FILES_java=	$(TARGDIR)/IBMCalendar.java			\
			$(TARGDIR)/CalendarAstronomer.java	\
			$(TARGDIR)/CalendarCache.java		\
			$(TARGDIR)/BuddhistCalendar.java	\
			$(TARGDIR)/ChineseCalendar.java		\
			$(TARGDIR)/HebrewCalendar.java		\
			$(TARGDIR)/IslamicCalendar.java		\
			$(TARGDIR)/JapaneseCalendar.java	\
												\
			$(TARGDIR)/DateRule.java			\
			$(TARGDIR)/EasterHoliday.java		\
			$(TARGDIR)/HebrewHoliday.java		\
			$(TARGDIR)/Holiday.java				\
			$(TARGDIR)/RangeDateRule.java		\
			$(TARGDIR)/SimpleDateRule.java		\
			$(TARGDIR)/SimpleHoliday.java		\
												\
			$(TARGDIR)/Utility.java				\
			$(TARGDIR)/CompactByteArray.java	\
			$(TARGDIR)/CompactCharArray.java	\



include $(TOPDIR)/src/build/rules.gmk


