%1\genrb \icu\data\default.txt
%1\genrb \icu\data\index.txt
%1\genrb \icu\data\ar.txt
%1\genrb \icu\data\ar_AE.txt
%1\genrb \icu\data\ar_BH.txt
%1\genrb \icu\data\ar_DZ.txt
%1\genrb \icu\data\ar_EG.txt
%1\genrb \icu\data\ar_IQ.txt
%1\genrb \icu\data\ar_JO.txt
%1\genrb \icu\data\ar_KW.txt
%1\genrb \icu\data\ar_LB.txt
%1\genrb \icu\data\ar_LY.txt
%1\genrb \icu\data\ar_MA.txt
%1\genrb \icu\data\ar_OM.txt
%1\genrb \icu\data\ar_QA.txt
%1\genrb \icu\data\ar_SA.txt
%1\genrb \icu\data\ar_SD.txt
%1\genrb \icu\data\ar_SY.txt
%1\genrb \icu\data\ar_TN.txt
%1\genrb \icu\data\ar_YE.txt
%1\genrb \icu\data\be.txt
%1\genrb \icu\data\be_BY.txt
%1\genrb \icu\data\bg.txt
%1\genrb \icu\data\bg_BG.txt
%1\genrb \icu\data\ca.txt
%1\genrb \icu\data\ca_ES.txt
%1\genrb \icu\data\ca_ES_EURO.txt
%1\genrb \icu\data\cs.txt
%1\genrb \icu\data\cs_CZ.txt
%1\genrb \icu\data\da.txt
%1\genrb \icu\data\da_DK.txt
%1\genrb \icu\data\de.txt
%1\genrb \icu\data\de_AT.txt
%1\genrb \icu\data\de_AT_EURO.txt
%1\genrb \icu\data\de_CH.txt
%1\genrb \icu\data\de_DE.txt
%1\genrb \icu\data\de_DE_EURO.txt
%1\genrb \icu\data\de_LU.txt
%1\genrb \icu\data\de_LU_EURO.txt
%1\genrb \icu\data\el.txt
%1\genrb \icu\data\el_GR.txt
%1\genrb \icu\data\en.txt
%1\genrb \icu\data\en_AU.txt
%1\genrb \icu\data\en_CA.txt
%1\genrb \icu\data\en_GB.txt
%1\genrb \icu\data\en_IE.txt
%1\genrb \icu\data\en_IE_EURO.txt
%1\genrb \icu\data\en_NZ.txt
%1\genrb \icu\data\en_US.txt
%1\genrb \icu\data\en_ZA.txt
%1\genrb \icu\data\es.txt
%1\genrb \icu\data\es_AR.txt
%1\genrb \icu\data\es_BO.txt
%1\genrb \icu\data\es_CL.txt
%1\genrb \icu\data\es_CO.txt
%1\genrb \icu\data\es_CR.txt
%1\genrb \icu\data\es_DO.txt
%1\genrb \icu\data\es_EC.txt
%1\genrb \icu\data\es_ES.txt
%1\genrb \icu\data\es_ES_EURO.txt
%1\genrb \icu\data\es_GT.txt
%1\genrb \icu\data\es_HN.txt
%1\genrb \icu\data\es_MX.txt
%1\genrb \icu\data\es_NI.txt
%1\genrb \icu\data\es_PA.txt
%1\genrb \icu\data\es_PE.txt
%1\genrb \icu\data\es_PR.txt
%1\genrb \icu\data\es_PY.txt
%1\genrb \icu\data\es_SV.txt
%1\genrb \icu\data\es_UY.txt
%1\genrb \icu\data\es_VE.txt
%1\genrb \icu\data\et.txt
%1\genrb \icu\data\et_EE.txt
%1\genrb \icu\data\fi.txt
%1\genrb \icu\data\fi_FI.txt
%1\genrb \icu\data\fi_FI_EURO.txt
%1\genrb \icu\data\fr.txt
%1\genrb \icu\data\fr_BE.txt
%1\genrb \icu\data\fr_BE_EURO.txt
%1\genrb \icu\data\fr_CA.txt
%1\genrb \icu\data\fr_CH.txt
%1\genrb \icu\data\fr_FR.txt
%1\genrb \icu\data\fr_FR_EURO.txt
%1\genrb \icu\data\fr_LU.txt
%1\genrb \icu\data\fr_LU_EURO.txt
%1\genrb \icu\data\hr.txt
%1\genrb \icu\data\hr_HR.txt
%1\genrb \icu\data\hu.txt
%1\genrb \icu\data\hu_HU.txt
%1\genrb \icu\data\is.txt
%1\genrb \icu\data\is_IS.txt
%1\genrb \icu\data\it.txt
%1\genrb \icu\data\it_CH.txt
%1\genrb \icu\data\it_IT.txt
%1\genrb \icu\data\it_IT_EURO.txt
%1\genrb \icu\data\iw.txt
%1\genrb \icu\data\iw_IL.txt
%1\genrb \icu\data\ja.txt
%1\genrb \icu\data\ja_JP.txt
%1\genrb \icu\data\ko.txt
%1\genrb \icu\data\ko_KR.txt
%1\genrb \icu\data\lt.txt
%1\genrb \icu\data\lt_LT.txt
%1\genrb \icu\data\lv.txt
%1\genrb \icu\data\lv_LV.txt
%1\genrb \icu\data\mk.txt
%1\genrb \icu\data\mk_MK.txt
%1\genrb \icu\data\nl.txt
%1\genrb \icu\data\nl_BE.txt
%1\genrb \icu\data\nl_BE_EURO.txt
%1\genrb \icu\data\nl_NL.txt
%1\genrb \icu\data\nl_NL_EURO.txt
%1\genrb \icu\data\no.txt
%1\genrb \icu\data\no_NO.txt
%1\genrb \icu\data\no_NO_NY.txt
%1\genrb \icu\data\pl.txt
%1\genrb \icu\data\pl_PL.txt
%1\genrb \icu\data\pt.txt
%1\genrb \icu\data\pt_BR.txt
%1\genrb \icu\data\pt_PT.txt
%1\genrb \icu\data\pt_PT_EURO.txt
%1\genrb \icu\data\ro.txt
%1\genrb \icu\data\ro_RO.txt
%1\genrb \icu\data\ru.txt
%1\genrb \icu\data\ru_RU.txt
%1\genrb \icu\data\sh.txt
%1\genrb \icu\data\sh_YU.txt
%1\genrb \icu\data\sk.txt
%1\genrb \icu\data\sk_SK.txt
%1\genrb \icu\data\sl.txt
%1\genrb \icu\data\sl_SI.txt
%1\genrb \icu\data\sq.txt
%1\genrb \icu\data\sq_AL.txt
%1\genrb \icu\data\sr.txt
%1\genrb \icu\data\sr_YU.txt
%1\genrb \icu\data\sv.txt
%1\genrb \icu\data\sv_SE.txt
%1\genrb \icu\data\th.txt
%1\genrb \icu\data\th_TH.txt
%1\genrb \icu\data\tr.txt
%1\genrb \icu\data\tr_TR.txt
%1\genrb \icu\data\uk.txt
%1\genrb \icu\data\uk_UA.txt
%1\genrb \icu\data\zh.txt
%1\genrb \icu\data\zh_CN.txt
%1\genrb \icu\data\zh_HK.txt
%1\genrb \icu\data\zh_TW.txt
rem Do the conversion for the test locales
%1\genrb \icu\source\test\testdata\default.txt
%1\genrb \icu\source\test\testdata\te.txt
%1\genrb \icu\source\test\testdata\te_IN.txt


