#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:00 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.text.resources

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/NumberFormatRules.java	    \
			$(TARGDIR)/NumberFormatRules_de.java	\
			$(TARGDIR)/NumberFormatRules_el.java	\
			$(TARGDIR)/NumberFormatRules_en.java	\
			$(TARGDIR)/NumberFormatRules_en_GB.java	\
			$(TARGDIR)/NumberFormatRules_es.java	\
			$(TARGDIR)/NumberFormatRules_fr.java	\
			$(TARGDIR)/NumberFormatRules_fr_CH.java	\
			$(TARGDIR)/NumberFormatRules_it.java	\
			$(TARGDIR)/NumberFormatRules_iw.java	\
			$(TARGDIR)/NumberFormatRules_ja.java	\
			$(TARGDIR)/NumberFormatRules_nl.java	\
			$(TARGDIR)/NumberFormatRules_ru.java	\
			$(TARGDIR)/NumberFormatRules_sv.java	\
										            \
			$(TARGDIR)/BreakIteratorRules.java		\
			$(TARGDIR)/BreakIteratorRules_th.java   \
										\
			$(TARGDIR)/TransliterationRule$$Fullwidth$$Halfwidth.java	\
			$(TARGDIR)/TransliterationRule$$Han$$Pinyin.java			\
			$(TARGDIR)/TransliterationRule$$Kanji$$English.java		\
			$(TARGDIR)/TransliterationRule$$Kanji$$OnRomaji.java		\
			$(TARGDIR)/TransliterationRule$$KeyboardEscape$$Latin1.java	\
			$(TARGDIR)/TransliterationRule$$Latin$$Arabic.java		\
			$(TARGDIR)/TransliterationRule$$Latin$$Cyrillic.java		\
			$(TARGDIR)/TransliterationRule$$Latin$$Devanagari.java		\
			$(TARGDIR)/TransliterationRule$$Latin$$Greek.java			\
			$(TARGDIR)/TransliterationRule$$Latin$$Hebrew.java		\
			$(TARGDIR)/TransliterationRule$$Latin$$Jamo.java			\
			$(TARGDIR)/TransliterationRule$$Latin$$Kana.java			\
			$(TARGDIR)/TransliterationRule$$StraightQuotes$$CurlyQuotes.java	\
			$(TARGDIR)/TransliterationRule$$UnicodeName$$UnicodeChar.java	\
								\
			$(TARGDIR)/LocaleElements.java		\
			$(TARGDIR)/LocaleElements_en.java  	\



FILES_dict= $(TARGDIR)/thai_dict                    \


!include $(TOPDIR)/src/build/rules.mak
