#
# @(#)$RCSfile: makefile,v $ $Revision: 1.2 $ $Date: 2000/02/18 00:29:08 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.text.resources

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/NumberFormatRules.java	    \
			$(TARGDIR)/NumberFormatRules_de.java	\
			$(TARGDIR)/NumberFormatRules_el.java	\
			$(TARGDIR)/NumberFormatRules_en.java	\
			$(TARGDIR)/NumberFormatRules_en_GB.java	\
			$(TARGDIR)/NumberFormatRules_es.java	\
			$(TARGDIR)/NumberFormatRules_fr.java	\
			$(TARGDIR)/NumberFormatRules_fr_CH.java	\
			$(TARGDIR)/NumberFormatRules_it.java	\
			$(TARGDIR)/NumberFormatRules_iw.java	\
			$(TARGDIR)/NumberFormatRules_ja.java	\
			$(TARGDIR)/NumberFormatRules_nl.java	\
			$(TARGDIR)/NumberFormatRules_ru.java	\
			$(TARGDIR)/NumberFormatRules_sv.java	\
										            \
			$(TARGDIR)/BreakIteratorRules.java		\
			$(TARGDIR)/BreakIteratorRules_th.java   \
										\
			$(TARGDIR)/TransliterationRule_Fullwidth_Halfwidth.java	\
#			$(TARGDIR)/TransliterationRule_Han_Pinyin.java			\
			$(TARGDIR)/TransliterationRule_Kanji_English.java		\
			$(TARGDIR)/TransliterationRule_Kanji_OnRomaji.java		\
			$(TARGDIR)/TransliterationRule_KeyboardEscape_Latin1.java	\
			$(TARGDIR)/TransliterationRule_Latin_Arabic.java		\
			$(TARGDIR)/TransliterationRule_Latin_Cyrillic.java		\
			$(TARGDIR)/TransliterationRule_Latin_Devanagari.java		\
			$(TARGDIR)/TransliterationRule_Latin_Greek.java			\
			$(TARGDIR)/TransliterationRule_Latin_Hebrew.java		\
			$(TARGDIR)/TransliterationRule_Latin_Jamo.java			\
			$(TARGDIR)/TransliterationRule_Latin_Kana.java			\
			$(TARGDIR)/TransliterationRule_StraightQuotes_CurlyQuotes.java	\
			$(TARGDIR)/TransliterationRule_UnicodeName_UnicodeChar.java	\
								\
			$(TARGDIR)/LocaleElements.java		\
			$(TARGDIR)/LocaleElements_en.java  	\



FILES_dict= $(TARGDIR)/thai_dict                    \


!include $(TOPDIR)/src/build/rules.mak
