package com.ibm.text.resources;

import java.util.ListResourceBundle;

public class TransliterationRule$Latin$Greek extends ListResourceBundle {
    /**
     * Overrides ListResourceBundle
     */
    public Object[][] getContents() {
        return new Object[][] {
            { "Description",
                "Latin to Greek" },

            { "Rule",
                // Greek Letters

                "grAl=\u0391;"
                + "grBe=\u0392;"
                + "grGa=\u0393;"
                + "grDe=\u0394;"
                + "grEp=\u0395;"
                + "grZe=\u0396;"
                + "grEt=\u0397;"
                + "grTh=\u0398;"
                + "grIo=\u0399;"
                + "grKa=\u039A;"
                + "grLa=\u039B;"
                + "grMu=\u039C;"
                + "grNu=\u039D;"
                + "grKs=\u039E;"
                + "grOm=\u039F;"
                + "grPi=\u03A0;"
                + "grRh=\u03A1;"
                + "grSi=\u03A3;"
                + "grTa=\u03A4;"
                + "grUp=\u03A5;"
                + "grPh=\u03A6;"
                + "grKh=\u03A7;"
                + "grPs=\u03A8;"
                + "grOme=\u03A9;"

                + "gral=\u03B1;"
                + "grbe=\u03B2;"
                + "grga=\u03B3;"
                + "grde=\u03B4;"
                + "grep=\u03B5;"
                + "grze=\u03B6;"
                + "gret=\u03B7;"
                + "grth=\u03B8;"
                + "grio=\u03B9;"
                + "grka=\u03BA;"
                + "grla=\u03BB;"
                + "grmu=\u03BC;"
                + "grnu=\u03BD;"
                + "grks=\u03BE;"
                + "grom=\u03BF;"
                + "grpi=\u03C0;"
                + "grrh=\u03C1;"
                + "grsi=\u03C3;"
                + "grta=\u03C4;"
                + "grup=\u03C5;"
                + "grph=\u03C6;"
                + "grkh=\u03C7;"
                + "grps=\u03C8;"
                + "grome=\u03C9;"

                //forms
                + "grfinal=\u03C2;"

                + "grAcAl=\u0386;"
                + "grAcEp=\u0388;"
                + "grAcEt=\u0389;"
                + "grAcIo=\u038A;"
                + "grAcOm=\u038C;"
                + "grAcUp=\u038E;"
                + "grAcOme=\u038F;"
                + "grDiIo=\u03AA;"
                + "grDiUp=\u03AB;"

                + "gracal=\u03AC;"
                + "gracep=\u03AD;"
                + "gracet=\u03AE;"
                + "gracio=\u03AF;"
                + "gracom=\u03CC;"
                + "gracup=\u03CD;"
                + "gracome=\u03CE;"
                + "grdiio=\u03CA;"
                + "grdiup=\u03CB;"

                //gracdiio=\u00FD
                //gracdiup=\u00FE

                + "letter=[[:Lu:][:Ll:]];"

                // convert Roman to Native
                + "Greek>\u039c\u0397\u039d\u0399\u039d\u0020\u0391\u0395\u0399\u0394\u0395\u002c\u0020\u0398\u0395\u0391\u002c\u0020--\u0397\u039b\u0397\u0399\u0391\u0394\u0395\u03a9\u0020\u0391\u03a7\u0399\u039b\u0397\u039f\u03a3;"

                + "AV`>{grAl}{grAcUp};"
                + "EV`>{grEp}{grAcUp};"
                + "AV>{grAl}{grUp};"
                + "EV>{grEp}{grUp};"
                + "NG>{grGa}{grGa};"
                + "NK>{grGa}{grKa};"
                + "NX>{grGa}{grKs};"
                + "NCH>{grGa}{grKh};"

                //+ "final = [ .;];" // Syntax error, unused anyway - Liu

                + "A`>{grAcAl};"
                + "EE`>{grAcEt};"
                + "E`>{grAcEp};"
                + "I`>{grAcIo};"
                + "U`>{grAcUp};"
                + "OO`>{grAcOme};"
                + "O`>{grAcOm};"
                + "''I>{grDiIo};"
                + "''U>{grDiUp};"
                + "A>{grAl};"
                + "B>{grBe};"
                + "C[I>{grSi};"
                + "C[E>{grSi};"
                + "C[Y>{grSi};"
                + "CH>{grKh};"
                + "C>{grKa};"
                + "D>{grDe};"
                + "EE>{grEt};"
                + "E>{grEp};"
                + "F>{grPh};"
                + "G>{grGa};"
                + "H>{grKh};"
                + "I>{grIo};"
                + "J>{grIo};"
                + "KS>{grKs};"
                + "KH>{grKh};"
                + "K>{grKa};"
                + "L>{grLa};"
                + "M>{grMu};"
                + "N>{grNu};"
                + "OO>{grOme};"
                + "O>{grOm};"
                + "PS>{grPs};"
                + "PH>{grPh};"
                + "P>{grPi};"
                + "Q>{grKa};"
                + "R>{grRh};"
                + "S>{grSi};"
                + "TH>{grTh};"
                + "T>{grTa};"
                + "W>{grUp}{grUp};"
                + "U>{grUp};"
                + "V>{grUp};"
                + "X>{grKs};"
                + "Y>{grUp};"
                + "Z>{grZe};"

                //now Native to Roman

                + "AV<{grAl}{grUp};"
                + "EV<{grEp}{grUp};"
                + "AV`<{grAl}{grAcUp};"
                + "EV`<{grEp}{grAcUp};"
                + "N''<{grNu}[{grGa};"
                + "NG<{grGa}{grGa};"
                + "N''<{grNu}[{grKa};"
                + "NK<{grGa}{grKa};"
                + "N''<{grNu}[{grKs};"
                + "NX<{grGa}{grKs};"
                + "N''<{grNu}[{grKh};"
                + "NCH<{grGa}{grKh};"

                + "A<{grAl};"
                + "B<{grBe};"
                + "G<{grGa};"
                + "D<{grDe};"
                + "E''<{grEp}[{grEp};"
                + "E''<{grEp}[{grEt};"
                + "E''<{grEp}[{grAcEp};"
                + "E''<{grEp}[{grAcEt};"
                + "E<{grEp};"
                + "Z<{grZe};"
                + "EE<{grEt};"
                + "TH<{grTh};"
                + "I<{grIo};"
                + "K<{grKa};"
                + "L<{grLa};"
                + "M<{grMu};"
                + "N<{grNu};"
                + "X<{grKs};"
                + "O''<{grOm}[{grOm};"
                + "O''<{grOm}[{grOme};"
                + "O''<{grOm}[{grAcOm};"
                + "O''<{grOm}[{grAcOme};"
                + "O<{grOm};"
                + "P''<{grPi}[{grSi};"
                + "P''<{grPi}[{grfinal};"
                + "P<{grPi};"
                + "R<{grRh};"
                + "S<{grSi};"
                + "T<{grTa};"
                + "W<{grUp}{grUp};"

                + "V<{grUp}[{grAcAl};"
                + "V<{grUp}[{grAcEp};"
                + "V<{grUp}[{grAcEt};"
                + "V<{grUp}[{grAcIo};"
                + "V<{grUp}[{grAcOm};"
                + "V<{grUp}[{grAcUp};"
                + "V<{grUp}[{grAcOme};"

                + "V<{grUp}[{grAl};"
                + "V<{grUp}[{grEp};"
                + "V<{grUp}[{grEt};"
                + "V<{grUp}[{grIo};"
                + "V<{grUp}[{grOm};"
                //{grUp}[{grUp}<V
                + "V<{grUp}[{grOme};"

                + "U<{grUp};"
                + "PH<{grPh};"
                + "CH<{grKh};"
                + "PS<{grPs};"
                + "OO<{grOme};"
                //forms
                + "A`<{grAcAl};"
                + "E`<{grAcEp};"
                + "EE`<{grAcEt};"
                + "I`<{grAcIo};"
                + "O`<{grAcOm};"
                + "U`<{grAcUp};"
                + "OO`<{grAcOme};"
                + "''I<{grDiIo};"
                + "''U<{grDiUp};"

                //{gracdiio}<XX
                //{gracdiup}<XX
                  //{grfinal}<XX

                + "av`>{gral}{gracup};"
                + "ev`>{grep}{gracup};"
                + "av>{gral}{grup};"
                + "ev>{grep}{grup};"
                + "ng>{grga}{grga};"
                + "nk>{grga}{grka};"
                + "nx>{grga}{grks};"
                + "nch>{grga}{grkh};"

                + "a`>{gracal};"
                + "ee`>{gracet};"
                + "e`>{gracep};"
                + "i`>{gracio};"
                + "u`>{gracup};"
                + "oo`>{gracome};"
                + "o`>{gracom};"
                + "''i>{grdiio};"
                + "''u>{grdiup};"
                + "a>{gral};"
                + "b>{grbe};"
                + "c[i>{grsi};"
                + "c[e>{grsi};"
                + "c[y>{grsi};"
                + "ch>{grkh};"
                + "c>{grka};"
                + "d>{grde};"
                + "ee>{gret};"
                + "e>{grep};"
                + "f>{grph};"
                + "g>{grga};"
                + "h>{grkh};"
                + "i>{grio};"
                + "j>{grio};"
                + "ks>{grks};"
                + "kh>{grkh};"
                + "k>{grka};"
                + "l>{grla};"
                + "m>{grmu};"
                + "n>{grnu};"
                + "oo>{grome};"
                + "o>{grom};"
                + "ps>{grps};"
                + "ph>{grph};"
                + "p>{grpi};"
                + "q>{grka};"
                + "r>{grrh};"
                + "s>|{grfinal};"
                + "{grfinal}[{letter}>{grsi};"
                + "th>{grth};"
                + "t>{grta};"
                + "w>{grup}{grup};"
                + "u>{grup};"
                + "v>{grup};"
                + "x>{grks};"
                + "y>{grup};"
                + "z>{grze};"


                //forms
                + "''>;"
                //now native to roman

                + "av<{gral}{grup};"
                + "ev<{grep}{grup};"
                + "av`<{gral}{gracup};"
                + "ev`<{grep}{gracup};"
                + "n''<{grnu}[{grga};"
                + "ng<{grga}{grga};"
                + "n''<{grnu}[{grka};"
                + "nk<{grga}{grka};"
                + "n''<{grnu}[{grks};"
                + "nx<{grga}{grks};"
                + "n''<{grnu}[{grkh};"
                + "nch<{grga}{grkh};"

                + "a<{gral};"
                + "b<{grbe};"
                + "g<{grga};"
                + "d<{grde};"
                + "e''<{grep}[{grep};"
                + "e''<{grep}[{gret};"
                + "e''<{grep}[{gracep};"
                + "e''<{grep}[{gracet};"
                + "e<{grep};"
                + "z<{grze};"
                + "ee<{gret};"
                + "th<{grth};"
                + "i<{grio};"
                + "k<{grka};"
                + "l<{grla};"
                + "m<{grmu};"
                + "n<{grnu};"
                + "x<{grks};"
                + "o''<{grom}[{grom};"
                + "o''<{grom}[{grome};"
                + "o''<{grom}[{gracom};"
                + "o''<{grom}[{gracome};"
                + "o<{grom};"
                + "p''<{grpi}[{grsi};"
                + "p''<{grpi}[{grfinal};"
                + "p<{grpi};"
                + "r<{grrh};"
                + "s<{grsi};"
                + "s<{grfinal};"
                + "t<{grta};"
                + "w<{grup}{grup};"

                + "v<{grup}[{gracal};"
                + "v<{grup}[{gracep};"
                + "v<{grup}[{gracet};"
                + "v<{grup}[{gracio};"
                + "v<{grup}[{gracom};"
                + "v<{grup}[{gracup};"
                + "v<{grup}[{gracome};"

                + "v<{grup}[{gral};"
                + "v<{grup}[{grep};"
                + "v<{grup}[{gret};"
                + "v<{grup}[{grio};"
                + "v<{grup}[{grom};"
                //{grup}[{grup}<v
                + "v<{grup}[{grome};"

                + "u<{grup};"
                + "ph<{grph};"
                + "ch<{grkh};"
                + "ps<{grps};"
                + "oo<{grome};"
                //forms
                + "a`<{gracal};"
                + "e`<{gracep};"
                + "ee`<{gracet};"
                + "i`<{gracio};"
                + "o`<{gracom};"
                + "u`<{gracup};"
                + "oo`<{gracome};"
                + "''i<{grdiio};"
                + "''u<{grdiup};"
                + "<'';"

                //{gracdiio}<xx
                //{gracdiup}<xx
                //{grfinal}<xx
            }
        };
    }
}
