#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:42 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.demo.calendar

include $(TOPDIR)/src/build/defs.gmk

FILES_java=	$(TARGDIR)/CalendarApp.java			\
			$(TARGDIR)/CalendarFrame.java		\
			$(TARGDIR)/CalendarPanel.java		\
			$(TARGDIR)/CalendarCalc.java		\

include $(TOPDIR)/src/build/rules.gmk
