#
# @(#)$RCSfile: makefile,v $ $Revision: 1.3 $ $Date: 2000/03/07 23:23:39 $
#

TOPDIR=	../../../../..
PACKAGE=	com.ibm.demo.rbbi

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/TextBoundDemo.java	\
		$(TARGDIR)/DBBIDemo.java	\
		$(TARGDIR)/BreakIteratorRules_en_US_DEMO.java	\

FILES_dict= $(TARGDIR)/english.dict \

!include $(TOPDIR)/src/build/rules.mak

