#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:41 $
#

TOPDIR=	../../../../..
PACKAGE=	com.ibm.demo.RuleBasedBreakIterator

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/TextBoundDemo.java	\
		$(TARGDIR)/DBBIDemo.java	\
		$(TARGDIR)/BreakIteratorRules_en_US_TEST.java	\

FILES_dict= $(TARGDIR)/english.dict \

!include $(TOPDIR)/src/build/rules.mak

