#
# @(#)$RCSfile: makefile,v $ $Revision: 1.2 $ $Date: 2000/03/02 00:39:50 $
#

TOPDIR=	../../../../..
PACKAGE=	com.ibm.demo.rbbi

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/TextBoundDemo.java	\
		$(TARGDIR)/DBBIDemo.java	\
		$(TARGDIR)/BreakIteratorRules_en_US_TEST.java	\

FILES_dict= $(TARGDIR)/english.dict \

!include $(TOPDIR)/src/build/rules.mak

