#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:50 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.compression

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/Main.java			\
			$(TARGDIR)/Test.java	\


include $(TOPDIR)/src/build/rules.gmk
