#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/25 23:26:15 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.compression

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/ExhaustiveTest.java			\
			$(TARGDIR)/DecompressionTest.java	\


include $(TOPDIR)/src/build/rules.gmk
