#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:51 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.compression

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/Main.java			\
			$(TARGDIR)/Test.java	\


!include $(TOPDIR)/src/build/rules.mak
