#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:02 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.tools.RuleBasedBreakIterator

include $(TOPDIR)/src/build/defs.gmk

FILES_java=	\
    $(TARGDIR)/../../util/CompactByteArray.java  \
    $(TARGDIR)/../../text/CharSet.java  \
    $(TARGDIR)/BuildDictionaryFile.java \
		

include $(TOPDIR)/src/build/rules.gmk
