/*
*******************************************************************************
*   Copyright (C) 2004, International Business Machines
*   Corporation and others.  All Rights Reserved.
*******************************************************************************
*
*   file name:  udraft.h
*   encoding:   US-ASCII
*   tab size:   8 (not used)
*   indentation:4
*
*   Created by: gendraft.pl, a perl script written by Ram Viswanadha
*
*  Contains data for commenting out APIs.
*  Gets included by umachine.h
*
*  THIS FILE IS MACHINE-GENERATED, DON'T PLAY WITH IT IF YOU DON'T KNOW WHAT
*  YOU ARE DOING, OTHERWISE VERY BAD THINGS WILL HAPPEN!
*/

#ifndef UDRAFT_H
#define UDRAFT_H

#ifdef U_HIDE_DRAFT_API

#define URegistryKey_2_8 URegistryKey_DRAFT_API_DO_NOT_USE
#define ULineBreakTag_2_8 ULineBreakTag_DRAFT_API_DO_NOT_USE
#define USentenceBreakTag_2_8 USentenceBreakTag_DRAFT_API_DO_NOT_USE
#define ULineBreakTag_2_8 ULineBreakTag_DRAFT_API_DO_NOT_USE
#define USentenceBreakTag_2_8 USentenceBreakTag_DRAFT_API_DO_NOT_USE
#define ubrk_getLocaleByType_2_8 ubrk_getLocaleByType_DRAFT_API_DO_NOT_USE
#define ubrk_getRuleStatusVec_2_8 ubrk_getRuleStatusVec_DRAFT_API_DO_NOT_USE
#define UCAL_EXTENDED_YEAR_2_8 UCAL_EXTENDED_YEAR_DRAFT_API_DO_NOT_USE
#define UCAL_JULIAN_DAY_2_8 UCAL_JULIAN_DAY_DRAFT_API_DO_NOT_USE
#define UCAL_MILLISECONDS_IN_DAY_2_8 UCAL_MILLISECONDS_IN_DAY_DRAFT_API_DO_NOT_USE
#define UCAL_DAY_OF_MONTH_2_8 UCAL_DAY_OF_MONTH_DRAFT_API_DO_NOT_USE
#define ucal_getDSTSavings_2_8 ucal_getDSTSavings_DRAFT_API_DO_NOT_USE
#define ucal_getDefaultTimeZone_2_8 ucal_getDefaultTimeZone_DRAFT_API_DO_NOT_USE
#define ucal_getLocaleByType_2_8 ucal_getLocaleByType_DRAFT_API_DO_NOT_USE
#define ucal_openCountryTimeZones_2_8 ucal_openCountryTimeZones_DRAFT_API_DO_NOT_USE
#define ucal_openTimeZones_2_8 ucal_openTimeZones_DRAFT_API_DO_NOT_USE
#define ucal_setDefaultTimeZone_2_8 ucal_setDefaultTimeZone_DRAFT_API_DO_NOT_USE
#define u_catclose_2_8 u_catclose_DRAFT_API_DO_NOT_USE
#define u_catgets_2_8 u_catgets_DRAFT_API_DO_NOT_USE
#define u_catopen_2_8 u_catopen_DRAFT_API_DO_NOT_USE
#define u_nl_catd_2_8 u_nl_catd_DRAFT_API_DO_NOT_USE
#define UHangulSyllableType_2_8 UHangulSyllableType_DRAFT_API_DO_NOT_USE
#define UBLOCK_NO_BLOCK_2_8 UBLOCK_NO_BLOCK_DRAFT_API_DO_NOT_USE
#define UBLOCK_LIMBU_2_8 UBLOCK_LIMBU_DRAFT_API_DO_NOT_USE
#define UBLOCK_TAI_LE_2_8 UBLOCK_TAI_LE_DRAFT_API_DO_NOT_USE
#define UBLOCK_KHMER_SYMBOLS_2_8 UBLOCK_KHMER_SYMBOLS_DRAFT_API_DO_NOT_USE
#define UBLOCK_PHONETIC_EXTENSIONS_2_8 UBLOCK_PHONETIC_EXTENSIONS_DRAFT_API_DO_NOT_USE
#define UBLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS_2_8 UBLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS_DRAFT_API_DO_NOT_USE
#define UBLOCK_YIJING_HEXAGRAM_SYMBOLS_2_8 UBLOCK_YIJING_HEXAGRAM_SYMBOLS_DRAFT_API_DO_NOT_USE
#define UBLOCK_LINEAR_B_SYLLABARY_2_8 UBLOCK_LINEAR_B_SYLLABARY_DRAFT_API_DO_NOT_USE
#define UBLOCK_LINEAR_B_IDEOGRAMS_2_8 UBLOCK_LINEAR_B_IDEOGRAMS_DRAFT_API_DO_NOT_USE
#define UBLOCK_AEGEAN_NUMBERS_2_8 UBLOCK_AEGEAN_NUMBERS_DRAFT_API_DO_NOT_USE
#define UBLOCK_UGARITIC_2_8 UBLOCK_UGARITIC_DRAFT_API_DO_NOT_USE
#define UBLOCK_SHAVIAN_2_8 UBLOCK_SHAVIAN_DRAFT_API_DO_NOT_USE
#define UBLOCK_OSMANYA_2_8 UBLOCK_OSMANYA_DRAFT_API_DO_NOT_USE
#define UBLOCK_CYPRIOT_SYLLABARY_2_8 UBLOCK_CYPRIOT_SYLLABARY_DRAFT_API_DO_NOT_USE
#define UBLOCK_TAI_XUAN_JING_SYMBOLS_2_8 UBLOCK_TAI_XUAN_JING_SYMBOLS_DRAFT_API_DO_NOT_USE
#define UBLOCK_VARIATION_SELECTORS_SUPPLEMENT_2_8 UBLOCK_VARIATION_SELECTORS_SUPPLEMENT_DRAFT_API_DO_NOT_USE
#define UHangulSyllableType_2_8 UHangulSyllableType_DRAFT_API_DO_NOT_USE
#define U_JG_FE_2_8 U_JG_FE_DRAFT_API_DO_NOT_USE
#define U_JG_KHAPH_2_8 U_JG_KHAPH_DRAFT_API_DO_NOT_USE
#define U_JG_ZHAIN_2_8 U_JG_ZHAIN_DRAFT_API_DO_NOT_USE
#define UCHAR_CASE_SENSITIVE_2_8 UCHAR_CASE_SENSITIVE_DRAFT_API_DO_NOT_USE
#define UCHAR_HANGUL_SYLLABLE_TYPE_2_8 UCHAR_HANGUL_SYLLABLE_TYPE_DRAFT_API_DO_NOT_USE
#define u_isISOControl_2_8 u_isISOControl_DRAFT_API_DO_NOT_USE
#define u_isJavaSpaceChar_2_8 u_isJavaSpaceChar_DRAFT_API_DO_NOT_USE
#define u_isblank_2_8 u_isblank_DRAFT_API_DO_NOT_USE
#define u_isgraph_2_8 u_isgraph_DRAFT_API_DO_NOT_USE
#define u_ispunct_2_8 u_ispunct_DRAFT_API_DO_NOT_USE
#define u_isxdigit_2_8 u_isxdigit_DRAFT_API_DO_NOT_USE
#define UMTX_2_8 UMTX_DRAFT_API_DO_NOT_USE
#define UMemAllocFn_2_8 UMemAllocFn_DRAFT_API_DO_NOT_USE
#define UMemFreeFn_2_8 UMemFreeFn_DRAFT_API_DO_NOT_USE
#define UMemReallocFn_2_8 UMemReallocFn_DRAFT_API_DO_NOT_USE
#define UMtxAtomicFn_2_8 UMtxAtomicFn_DRAFT_API_DO_NOT_USE
#define UMtxFn_2_8 UMtxFn_DRAFT_API_DO_NOT_USE
#define UMtxInitFn_2_8 UMtxInitFn_DRAFT_API_DO_NOT_USE
#define u_init_2_8 u_init_DRAFT_API_DO_NOT_USE
#define u_setAtomicIncDecFunctions_2_8 u_setAtomicIncDecFunctions_DRAFT_API_DO_NOT_USE
#define u_setMemoryFunctions_2_8 u_setMemoryFunctions_DRAFT_API_DO_NOT_USE
#define u_setMutexFunctions_2_8 u_setMutexFunctions_DRAFT_API_DO_NOT_USE
#define UCNV_GET_MAX_BYTES_FOR_STRING_2_8 UCNV_GET_MAX_BYTES_FOR_STRING_DRAFT_API_DO_NOT_USE
#define UConverterUnicodeSet_2_8 UConverterUnicodeSet_DRAFT_API_DO_NOT_USE
#define UConverterUnicodeSet_2_8 UConverterUnicodeSet_DRAFT_API_DO_NOT_USE
#define UCNV_ROUNDTRIP_SET_2_8 UCNV_ROUNDTRIP_SET_DRAFT_API_DO_NOT_USE
#define UCNV_SET_COUNT_2_8 UCNV_SET_COUNT_DRAFT_API_DO_NOT_USE
#define ucnv_convertEx_2_8 ucnv_convertEx_DRAFT_API_DO_NOT_USE
#define ucnv_fromAlgorithmic_2_8 ucnv_fromAlgorithmic_DRAFT_API_DO_NOT_USE
#define ucnv_getUnicodeSet_2_8 ucnv_getUnicodeSet_DRAFT_API_DO_NOT_USE
#define ucnv_toAlgorithmic_2_8 ucnv_toAlgorithmic_DRAFT_API_DO_NOT_USE
#define ucol_getLocaleByType_2_8 ucol_getLocaleByType_DRAFT_API_DO_NOT_USE
#define ucol_getUCAVersion_2_8 ucol_getUCAVersion_DRAFT_API_DO_NOT_USE
#define ucol_nextSortKeyPart_2_8 ucol_nextSortKeyPart_DRAFT_API_DO_NOT_USE
#define ucol_strcollIter_2_8 ucol_strcollIter_DRAFT_API_DO_NOT_USE
#define ucol_primaryOrder_2_8 ucol_primaryOrder_DRAFT_API_DO_NOT_USE
#define ucol_secondaryOrder_2_8 ucol_secondaryOrder_DRAFT_API_DO_NOT_USE
#define ucol_tertiaryOrder_2_8 ucol_tertiaryOrder_DRAFT_API_DO_NOT_USE
#define UCONFIG_NO_IDNA_2_8 UCONFIG_NO_IDNA_DRAFT_API_DO_NOT_USE
#define UCONFIG_NO_NORMALIZATION_2_8 UCONFIG_NO_NORMALIZATION_DRAFT_API_DO_NOT_USE
#define UCONFIG_NO_SERVICE_2_8 UCONFIG_NO_SERVICE_DRAFT_API_DO_NOT_USE
#define UCurrNameStyle_2_8 UCurrNameStyle_DRAFT_API_DO_NOT_USE
#define UCurrNameStyle_2_8 UCurrNameStyle_DRAFT_API_DO_NOT_USE
#define UCURR_SYMBOL_NAME_2_8 UCURR_SYMBOL_NAME_DRAFT_API_DO_NOT_USE
#define UCURR_LONG_NAME_2_8 UCURR_LONG_NAME_DRAFT_API_DO_NOT_USE
#define ucurr_forLocale_2_8 ucurr_forLocale_DRAFT_API_DO_NOT_USE
#define ucurr_getDefaultFractionDigits_2_8 ucurr_getDefaultFractionDigits_DRAFT_API_DO_NOT_USE
#define ucurr_getName_2_8 ucurr_getName_DRAFT_API_DO_NOT_USE
#define ucurr_getRoundingIncrement_2_8 ucurr_getRoundingIncrement_DRAFT_API_DO_NOT_USE
#define ucurr_register_2_8 ucurr_register_DRAFT_API_DO_NOT_USE
#define UDateFormatField_2_8 UDateFormatField_DRAFT_API_DO_NOT_USE
#define UDateFormatField_2_8 UDateFormatField_DRAFT_API_DO_NOT_USE
#define UDAT_ERA_FIELD_2_8 UDAT_ERA_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_YEAR_FIELD_2_8 UDAT_YEAR_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_MONTH_FIELD_2_8 UDAT_MONTH_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_DATE_FIELD_2_8 UDAT_DATE_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_HOUR_OF_DAY1_FIELD_2_8 UDAT_HOUR_OF_DAY1_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_HOUR_OF_DAY0_FIELD_2_8 UDAT_HOUR_OF_DAY0_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_MINUTE_FIELD_2_8 UDAT_MINUTE_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_SECOND_FIELD_2_8 UDAT_SECOND_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_FRACTIONAL_SECOND_FIELD_2_8 UDAT_FRACTIONAL_SECOND_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_DAY_OF_WEEK_FIELD_2_8 UDAT_DAY_OF_WEEK_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_DAY_OF_YEAR_FIELD_2_8 UDAT_DAY_OF_YEAR_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_DAY_OF_WEEK_IN_MONTH_FIELD_2_8 UDAT_DAY_OF_WEEK_IN_MONTH_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_WEEK_OF_YEAR_FIELD_2_8 UDAT_WEEK_OF_YEAR_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_WEEK_OF_MONTH_FIELD_2_8 UDAT_WEEK_OF_MONTH_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_AM_PM_FIELD_2_8 UDAT_AM_PM_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_HOUR1_FIELD_2_8 UDAT_HOUR1_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_HOUR0_FIELD_2_8 UDAT_HOUR0_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_TIMEZONE_FIELD_2_8 UDAT_TIMEZONE_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_YEAR_WOY_FIELD_2_8 UDAT_YEAR_WOY_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_DOW_LOCAL_FIELD_2_8 UDAT_DOW_LOCAL_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_EXTENDED_YEAR_FIELD_2_8 UDAT_EXTENDED_YEAR_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_JULIAN_DAY_FIELD_2_8 UDAT_JULIAN_DAY_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_MILLISECONDS_IN_DAY_FIELD_2_8 UDAT_MILLISECONDS_IN_DAY_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_TIMEZONE_RFC_FIELD_2_8 UDAT_TIMEZONE_RFC_FIELD_DRAFT_API_DO_NOT_USE
#define UDAT_FIELD_COUNT_2_8 UDAT_FIELD_COUNT_DRAFT_API_DO_NOT_USE
#define udat_getLocaleByType_2_8 udat_getLocaleByType_DRAFT_API_DO_NOT_USE
#define UIDNA_ALLOW_UNASSIGNED_2_8 UIDNA_ALLOW_UNASSIGNED_DRAFT_API_DO_NOT_USE
#define UIDNA_DEFAULT_2_8 UIDNA_DEFAULT_DRAFT_API_DO_NOT_USE
#define UIDNA_USE_STD3_RULES_2_8 UIDNA_USE_STD3_RULES_DRAFT_API_DO_NOT_USE
#define uidna_IDNToASCII_2_8 uidna_IDNToASCII_DRAFT_API_DO_NOT_USE
#define uidna_IDNToUnicode_2_8 uidna_IDNToUnicode_DRAFT_API_DO_NOT_USE
#define uidna_compare_2_8 uidna_compare_DRAFT_API_DO_NOT_USE
#define uidna_toASCII_2_8 uidna_toASCII_DRAFT_API_DO_NOT_USE
#define uidna_toUnicode_2_8 uidna_toUnicode_DRAFT_API_DO_NOT_USE
#define UITER_NO_STATE_2_8 UITER_NO_STATE_DRAFT_API_DO_NOT_USE
#define UCharIteratorGetState_2_8 UCharIteratorGetState_DRAFT_API_DO_NOT_USE
#define UCharIteratorSetState_2_8 UCharIteratorSetState_DRAFT_API_DO_NOT_USE
#define UITER_UNKNOWN_INDEX_2_8 UITER_UNKNOWN_INDEX_DRAFT_API_DO_NOT_USE
#define uiter_getState_2_8 uiter_getState_DRAFT_API_DO_NOT_USE
#define uiter_setState_2_8 uiter_setState_DRAFT_API_DO_NOT_USE
#define uiter_setUTF16BE_2_8 uiter_setUTF16BE_DRAFT_API_DO_NOT_USE
#define uiter_setUTF8_2_8 uiter_setUTF8_DRAFT_API_DO_NOT_USE
#define ULOC_KEYWORDS_CAPACITY_2_8 ULOC_KEYWORDS_CAPACITY_DRAFT_API_DO_NOT_USE
#define ULOC_KEYWORD_AND_VALUES_CAPACITY_2_8 ULOC_KEYWORD_AND_VALUES_CAPACITY_DRAFT_API_DO_NOT_USE
#define ULOC_KEYWORD_ASSIGN_2_8 ULOC_KEYWORD_ASSIGN_DRAFT_API_DO_NOT_USE
#define ULOC_KEYWORD_ITEM_SEPARATOR_2_8 ULOC_KEYWORD_ITEM_SEPARATOR_DRAFT_API_DO_NOT_USE
#define ULOC_KEYWORD_SEPARATOR_2_8 ULOC_KEYWORD_SEPARATOR_DRAFT_API_DO_NOT_USE
#define ULOC_SCRIPT_CAPACITY_2_8 ULOC_SCRIPT_CAPACITY_DRAFT_API_DO_NOT_USE
#define uloc_getBaseName_2_8 uloc_getBaseName_DRAFT_API_DO_NOT_USE
#define uloc_getDisplayKeyword_2_8 uloc_getDisplayKeyword_DRAFT_API_DO_NOT_USE
#define uloc_getDisplayKeywordValue_2_8 uloc_getDisplayKeywordValue_DRAFT_API_DO_NOT_USE
#define uloc_getDisplayScript_2_8 uloc_getDisplayScript_DRAFT_API_DO_NOT_USE
#define uloc_getKeywordValue_2_8 uloc_getKeywordValue_DRAFT_API_DO_NOT_USE
#define uloc_getScript_2_8 uloc_getScript_DRAFT_API_DO_NOT_USE
#define uloc_openKeywords_2_8 uloc_openKeywords_DRAFT_API_DO_NOT_USE
#define UMeasurementSystem_2_8 UMeasurementSystem_DRAFT_API_DO_NOT_USE
#define UMeasurementSystem_2_8 UMeasurementSystem_DRAFT_API_DO_NOT_USE
#define ulocdata_getExemplarSet_2_8 ulocdata_getExemplarSet_DRAFT_API_DO_NOT_USE
#define ulocdata_getMeasurementSystem_2_8 ulocdata_getMeasurementSystem_DRAFT_API_DO_NOT_USE
#define ulocdata_getPaperSize_2_8 ulocdata_getPaperSize_DRAFT_API_DO_NOT_USE
#define UINT64_C_2_8 UINT64_C_DRAFT_API_DO_NOT_USE
#define umsg_getLocaleByType_2_8 umsg_getLocaleByType_DRAFT_API_DO_NOT_USE
#define UNORM_COMPARE_NORM_OPTIONS_SHIFT_2_8 UNORM_COMPARE_NORM_OPTIONS_SHIFT_DRAFT_API_DO_NOT_USE
#define UNORM_UNICODE_3_2_2_8 UNORM_UNICODE_3_2_DRAFT_API_DO_NOT_USE
#define unorm_isNormalizedWithOptions_2_8 unorm_isNormalizedWithOptions_DRAFT_API_DO_NOT_USE
#define unorm_quickCheckWithOptions_2_8 unorm_quickCheckWithOptions_DRAFT_API_DO_NOT_USE
#define UNUM_MIN_SIGNIFICANT_DIGITS_2_8 UNUM_MIN_SIGNIFICANT_DIGITS_DRAFT_API_DO_NOT_USE
#define UNUM_MAX_SIGNIFICANT_DIGITS_2_8 UNUM_MAX_SIGNIFICANT_DIGITS_DRAFT_API_DO_NOT_USE
#define UNUM_LENIENT_PARSE_2_8 UNUM_LENIENT_PARSE_DRAFT_API_DO_NOT_USE
#define UNUM_PATTERN_DECIMAL_2_8 UNUM_PATTERN_DECIMAL_DRAFT_API_DO_NOT_USE
#define UNUM_ORDINAL_2_8 UNUM_ORDINAL_DRAFT_API_DO_NOT_USE
#define UNUM_DURATION_2_8 UNUM_DURATION_DRAFT_API_DO_NOT_USE
#define UNUM_PATTERN_RULEBASED_2_8 UNUM_PATTERN_RULEBASED_DRAFT_API_DO_NOT_USE
#define UNUM_SIGNIFICANT_DIGIT_SYMBOL_2_8 UNUM_SIGNIFICANT_DIGIT_SYMBOL_DRAFT_API_DO_NOT_USE
#define UNUM_DEFAULT_RULESET_2_8 UNUM_DEFAULT_RULESET_DRAFT_API_DO_NOT_USE
#define UNUM_PUBLIC_RULESETS_2_8 UNUM_PUBLIC_RULESETS_DRAFT_API_DO_NOT_USE
#define unum_getLocaleByType_2_8 unum_getLocaleByType_DRAFT_API_DO_NOT_USE
#define unum_parseInt64_2_8 unum_parseInt64_DRAFT_API_DO_NOT_USE
#define U_HAVE_PLACEMENT_NEW_2_8 U_HAVE_PLACEMENT_NEW_DRAFT_API_DO_NOT_USE
#define URegularExpression_2_8 URegularExpression_DRAFT_API_DO_NOT_USE
#define UREGEX_CANON_EQ_2_8 UREGEX_CANON_EQ_DRAFT_API_DO_NOT_USE
#define UREGEX_UWORD_2_8 UREGEX_UWORD_DRAFT_API_DO_NOT_USE
#define uregex_appendReplacement_2_8 uregex_appendReplacement_DRAFT_API_DO_NOT_USE
#define uregex_appendTail_2_8 uregex_appendTail_DRAFT_API_DO_NOT_USE
#define uregex_clone_2_8 uregex_clone_DRAFT_API_DO_NOT_USE
#define uregex_close_2_8 uregex_close_DRAFT_API_DO_NOT_USE
#define uregex_end_2_8 uregex_end_DRAFT_API_DO_NOT_USE
#define uregex_find_2_8 uregex_find_DRAFT_API_DO_NOT_USE
#define uregex_findNext_2_8 uregex_findNext_DRAFT_API_DO_NOT_USE
#define uregex_flags_2_8 uregex_flags_DRAFT_API_DO_NOT_USE
#define uregex_getText_2_8 uregex_getText_DRAFT_API_DO_NOT_USE
#define uregex_group_2_8 uregex_group_DRAFT_API_DO_NOT_USE
#define uregex_groupCount_2_8 uregex_groupCount_DRAFT_API_DO_NOT_USE
#define uregex_lookingAt_2_8 uregex_lookingAt_DRAFT_API_DO_NOT_USE
#define uregex_matches_2_8 uregex_matches_DRAFT_API_DO_NOT_USE
#define uregex_open_2_8 uregex_open_DRAFT_API_DO_NOT_USE
#define uregex_openC_2_8 uregex_openC_DRAFT_API_DO_NOT_USE
#define uregex_pattern_2_8 uregex_pattern_DRAFT_API_DO_NOT_USE
#define uregex_replaceAll_2_8 uregex_replaceAll_DRAFT_API_DO_NOT_USE
#define uregex_replaceFirst_2_8 uregex_replaceFirst_DRAFT_API_DO_NOT_USE
#define uregex_reset_2_8 uregex_reset_DRAFT_API_DO_NOT_USE
#define uregex_setText_2_8 uregex_setText_DRAFT_API_DO_NOT_USE
#define uregex_split_2_8 uregex_split_DRAFT_API_DO_NOT_USE
#define uregex_start_2_8 uregex_start_DRAFT_API_DO_NOT_USE
#define URES_NONE_2_8 URES_NONE_DRAFT_API_DO_NOT_USE
#define URES_STRING_2_8 URES_STRING_DRAFT_API_DO_NOT_USE
#define URES_BINARY_2_8 URES_BINARY_DRAFT_API_DO_NOT_USE
#define URES_TABLE_2_8 URES_TABLE_DRAFT_API_DO_NOT_USE
#define URES_ALIAS_2_8 URES_ALIAS_DRAFT_API_DO_NOT_USE
#define URES_INT_2_8 URES_INT_DRAFT_API_DO_NOT_USE
#define URES_ARRAY_2_8 URES_ARRAY_DRAFT_API_DO_NOT_USE
#define URES_INT_VECTOR_2_8 URES_INT_VECTOR_DRAFT_API_DO_NOT_USE
#define ures_getLocaleByType_2_8 ures_getLocaleByType_DRAFT_API_DO_NOT_USE
#define USCRIPT_CANADIAN_ABORIGINAL_2_8 USCRIPT_CANADIAN_ABORIGINAL_DRAFT_API_DO_NOT_USE
#define uset_addAll_2_8 uset_addAll_DRAFT_API_DO_NOT_USE
#define uset_applyPattern_2_8 uset_applyPattern_DRAFT_API_DO_NOT_USE
#define USPREP_ALLOW_UNASSIGNED_2_8 USPREP_ALLOW_UNASSIGNED_DRAFT_API_DO_NOT_USE
#define USPREP_DEFAULT_2_8 USPREP_DEFAULT_DRAFT_API_DO_NOT_USE
#define UStringPrepProfile_2_8 UStringPrepProfile_DRAFT_API_DO_NOT_USE
#define usprep_close_2_8 usprep_close_DRAFT_API_DO_NOT_USE
#define usprep_open_2_8 usprep_open_DRAFT_API_DO_NOT_USE
#define usprep_prepare_2_8 usprep_prepare_DRAFT_API_DO_NOT_USE
#define u_strCompareIter_2_8 u_strCompareIter_DRAFT_API_DO_NOT_USE
#define U_IS_BMP_2_8 U_IS_BMP_DRAFT_API_DO_NOT_USE
#define U_IS_SUPPLEMENTARY_2_8 U_IS_SUPPLEMENTARY_DRAFT_API_DO_NOT_USE
#define UTraceData_2_8 UTraceData_DRAFT_API_DO_NOT_USE
#define UTraceEntry_2_8 UTraceEntry_DRAFT_API_DO_NOT_USE
#define UTraceExit_2_8 UTraceExit_DRAFT_API_DO_NOT_USE
#define UTraceFunctionNumber_2_8 UTraceFunctionNumber_DRAFT_API_DO_NOT_USE
#define UTraceLevel_2_8 UTraceLevel_DRAFT_API_DO_NOT_USE
#define UTraceFunctionNumber_2_8 UTraceFunctionNumber_DRAFT_API_DO_NOT_USE
#define UTraceLevel_2_8 UTraceLevel_DRAFT_API_DO_NOT_USE
#define UTRACE_OFF_2_8 UTRACE_OFF_DRAFT_API_DO_NOT_USE
#define UTRACE_ERROR_2_8 UTRACE_ERROR_DRAFT_API_DO_NOT_USE
#define UTRACE_WARNING_2_8 UTRACE_WARNING_DRAFT_API_DO_NOT_USE
#define UTRACE_OPEN_CLOSE_2_8 UTRACE_OPEN_CLOSE_DRAFT_API_DO_NOT_USE
#define UTRACE_INFO_2_8 UTRACE_INFO_DRAFT_API_DO_NOT_USE
#define UTRACE_VERBOSE_2_8 UTRACE_VERBOSE_DRAFT_API_DO_NOT_USE
#define utrace_format_2_8 utrace_format_DRAFT_API_DO_NOT_USE
#define utrace_functionName_2_8 utrace_functionName_DRAFT_API_DO_NOT_USE
#define utrace_getFunctions_2_8 utrace_getFunctions_DRAFT_API_DO_NOT_USE
#define utrace_getLevel_2_8 utrace_getLevel_DRAFT_API_DO_NOT_USE
#define utrace_setFunctions_2_8 utrace_setFunctions_DRAFT_API_DO_NOT_USE
#define utrace_setLevel_2_8 utrace_setLevel_DRAFT_API_DO_NOT_USE
#define utrace_vformat_2_8 utrace_vformat_DRAFT_API_DO_NOT_USE
#define utrans_getUnicodeID_2_8 utrans_getUnicodeID_DRAFT_API_DO_NOT_USE
#define utrans_openIDs_2_8 utrans_openIDs_DRAFT_API_DO_NOT_USE
#define utrans_openU_2_8 utrans_openU_DRAFT_API_DO_NOT_USE
#define utrans_unregisterID_2_8 utrans_unregisterID_DRAFT_API_DO_NOT_USE
#define U_LAYOUTEX_API_2_8 U_LAYOUTEX_API_DRAFT_API_DO_NOT_USE
#define U_ICU_VERSION_MINOR_NUM_2_8 U_ICU_VERSION_MINOR_NUM_DRAFT_API_DO_NOT_USE
#define U_ICU_VERSION_SHORT_2_8 U_ICU_VERSION_SHORT_DRAFT_API_DO_NOT_USE
#define U_ICU_VERSION_SUFFIX_2_8 U_ICU_VERSION_SUFFIX_DRAFT_API_DO_NOT_USE
#define unregister_2_8 unregister_DRAFT_API_DO_NOT_USE
#define unregister_2_8 unregister_DRAFT_API_DO_NOT_USE
#define unistr_2_8 unistr_DRAFT_API_DO_NOT_USE
#define UnicodeSet_2_8 UnicodeSet_DRAFT_API_DO_NOT_USE

#endif /* U_HIDE_DRAFT_API */
#endif /* UDRAFT_H */

