#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:34 $
# 

TOPDIR=		../..
PACKAGE=	com

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS=	ibm

!include $(TOPDIR)/src/build/rules.mak

