#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/27 04:40:32 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.normalizer

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/BasicTest.java			\
		$(TARGDIR)/ExhaustiveTest.java		\

include $(TOPDIR)/src/build/rules.gmk
