#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:52 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.normalizer

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/BasicTest.java			\
		$(TARGDIR)/ExhaustiveTest.java		\
		$(TARGDIR)/FooTest.java				\

!include $(TOPDIR)/src/build/rules.mak
