#
# $RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/25 18:23:15 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.topleveltest

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/TestAll.java   \


include $(TOPDIR)/src/build/rules.gmk
