#
# $RCSfile: GNUmakefile,v $ $Revision: 1.3 $ $Date: 2000/02/25 18:24:53 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.translit

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/TransliteratorTest.java   \
			$(TARGDIR)/UnicodeSetTest.java	\


include $(TOPDIR)/src/build/rules.gmk
