#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:55 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.translit

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/TransliteratorTest.java   \
			$(TARGDIR)/UnicodeSetTest.java	\


!include $(TOPDIR)/src/build/rules.mak
