#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/29 19:51:41 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.search

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/SearchTest.java			\


include $(TOPDIR)/src/build/rules.gmk