#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/26 22:00:56 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.bnf

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/SearchTest.java			\


include $(TOPDIR)/src/build/rules.gmk