#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/26 22:00:57 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.search

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/SearchTest.java			\

!include $(TOPDIR)/src/build/rules.mak
