#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:09 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.util.resources

include $(TOPDIR)/src/build/defs.gmk

FILES_java=	$(TARGDIR)/BuddhistCalendarSymbols.java		\
			$(TARGDIR)/BuddhistCalendarSymbols_ar.java	\
			$(TARGDIR)/BuddhistCalendarSymbols_hu.java	\
			$(TARGDIR)/BuddhistCalendarSymbols_th.java	\
			$(TARGDIR)/ChineseCalendarSymbols.java		\
			$(TARGDIR)/HebrewCalendarSymbols.java		\
			$(TARGDIR)/HebrewCalendarSymbols_fi.java	\
			$(TARGDIR)/HebrewCalendarSymbols_fr.java	\
			$(TARGDIR)/HebrewCalendarSymbols_hu.java	\
			$(TARGDIR)/HebrewCalendarSymbols_iw.java	\
			$(TARGDIR)/HebrewCalendarSymbols_nl.java	\
			$(TARGDIR)/IslamicCalendarSymbols.java		\
			$(TARGDIR)/IslamicCalendarSymbols_ar.java	\
			$(TARGDIR)/IslamicCalendarSymbols_fi.java	\
			$(TARGDIR)/IslamicCalendarSymbols_fr.java	\
			$(TARGDIR)/IslamicCalendarSymbols_hu.java	\
			$(TARGDIR)/IslamicCalendarSymbols_iw.java	\
			$(TARGDIR)/IslamicCalendarSymbols_nl.java	\
			$(TARGDIR)/JapaneseCalendarSymbols.java		\
			$(TARGDIR)/JapaneseCalendarSymbols_ja.java	\
			$(TARGDIR)/HolidayBundle.java				\
			$(TARGDIR)/HolidayBundle_da.java			\
			$(TARGDIR)/HolidayBundle_da_DK.java			\
			$(TARGDIR)/HolidayBundle_de.java			\
			$(TARGDIR)/HolidayBundle_de_AT.java			\
			$(TARGDIR)/HolidayBundle_de_DE.java			\
			$(TARGDIR)/HolidayBundle_el.java			\
			$(TARGDIR)/HolidayBundle_el_GR.java			\
			$(TARGDIR)/HolidayBundle_en.java			\
			$(TARGDIR)/HolidayBundle_en_CA.java			\
			$(TARGDIR)/HolidayBundle_en_GB.java			\
			$(TARGDIR)/HolidayBundle_en_US.java			\
			$(TARGDIR)/HolidayBundle_es.java			\
			$(TARGDIR)/HolidayBundle_es_MX.java			\
			$(TARGDIR)/HolidayBundle_fr.java			\
			$(TARGDIR)/HolidayBundle_fr_CA.java			\
			$(TARGDIR)/HolidayBundle_fr_FR.java			\
			$(TARGDIR)/HolidayBundle_it.java			\
			$(TARGDIR)/HolidayBundle_it_IT.java			\
			$(TARGDIR)/HolidayBundle_iw.java			\
			$(TARGDIR)/HolidayBundle_iw_IL.java			\
			$(TARGDIR)/HolidayBundle_ja_JP.java			\


include $(TOPDIR)/src/build/rules.gmk
