#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:07 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.tools.normalizer

!include $(TOPDIR)/src/build/defs.mak

FILES_java=	$(TARGDIR)/NormalizerBuilder.java			\
			$(TARGDIR)/MutableChar.java					\
			$(TARGDIR)/SourceWriter.java				\
			$(TARGDIR)/JavaWriter.java					\
			$(TARGDIR)/CPPWriter.java					\

!include $(TOPDIR)/src/build/rules.mak

