#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:01 $
#

TOPDIR=	../../../..
PACKAGE=	com.ibm.tools

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS=	normalizer RuleBasedBreakIterator compression

!include $(TOPDIR)/src/build/rules.mak

