#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/28 00:47:29 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.demo.translit

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/Demo.java			\
			$(TARGDIR)/DemoApplet.java	\


!include $(TOPDIR)/src/build/rules.mak
