//---------------------------------------------------------
// Copyright (C) 2003-2004, International Business Machines
// Corporation and others.  All Rights Reserved.
//---------------------------------------------------------
// Build tool: tz2icu
// Build date: Mon Oct 25 13:21:25 2004
// Olson source: ftp://elsie.nci.nih.gov/pub/
// Olson version: 2004e
//---------------------------------------------------------
// >> !!! >>   THIS IS A MACHINE-GENERATED FILE   << !!! <<
// >> !!! >>>            DO NOT EDIT             <<< !!! <<
//---------------------------------------------------------

package com.ibm.icu.impl;

public final class ZoneMetaData {
  public static final String[][] EQUIV = {
    { "Africa/Addis_Ababa", "EAT" },
    { "ART", "Africa/Cairo", "Egypt" },
    { "Africa/Harare", "CAT" },
    { "Africa/Tripoli", "Libya" },
    { "America/Adak", "America/Atka", "US/Aleutian" },
    { "AST", "America/Anchorage", "SystemV/YST9YDT", "US/Alaska" },
    { "AGT", "America/Argentina/Buenos_Aires", "America/Buenos_Aires" },
    { "America/Argentina/Catamarca", "America/Catamarca" },
    { "America/Argentina/Cordoba", "America/Cordoba", "America/Rosario" },
    { "America/Argentina/Jujuy", "America/Jujuy" },
    { "America/Argentina/Mendoza", "America/Mendoza" },
    { "America/Chicago", "CST", "CST6CDT", "SystemV/CST6CDT", "US/Central" },
    { "America/Denver", "America/Shiprock", "MST7MDT", "Navajo", "SystemV/MST7MDT", "US/Mountain" },
    { "America/Detroit", "US/Michigan" },
    { "America/Edmonton", "Canada/Mountain" },
    { "America/Halifax", "Canada/Atlantic", "SystemV/AST4ADT" },
    { "America/Havana", "Cuba" },
    { "America/Indiana/Knox", "America/Knox_IN", "US/Indiana-Starke" },
    { "America/Fort_Wayne", "America/Indiana/Indianapolis", "America/Indianapolis", "EST", "IET", "SystemV/EST5", "US/East-Indiana" },
    { "America/Jamaica", "Jamaica" },
    { "America/Los_Angeles", "PST", "PST8PDT", "SystemV/PST8PDT", "US/Pacific", "US/Pacific-New" },
    { "America/Kentucky/Louisville", "America/Louisville" },
    { "America/Manaus", "Brazil/West" },
    { "America/Mazatlan", "Mexico/BajaSur" },
    { "America/Mexico_City", "Mexico/General" },
    { "America/New_York", "EST5EDT", "SystemV/EST5EDT", "US/Eastern" },
    { "America/Noronha", "Brazil/DeNoronha" },
    { "America/Phoenix", "MST", "PNT", "SystemV/MST7", "US/Arizona" },
    { "America/Puerto_Rico", "PRT", "SystemV/AST4" },
    { "America/Regina", "Canada/East-Saskatchewan", "Canada/Saskatchewan", "SystemV/CST6" },
    { "America/Porto_Acre", "America/Rio_Branco", "Brazil/Acre" },
    { "America/Santiago", "Chile/Continental" },
    { "America/Sao_Paulo", "BET", "Brazil/East" },
    { "America/St_Johns", "CNT", "Canada/Newfoundland" },
    { "America/St_Thomas", "America/Virgin" },
    { "America/Ensenada", "America/Tijuana", "Mexico/BajaNorte" },
    { "America/Toronto", "Canada/Eastern" },
    { "America/Vancouver", "Canada/Pacific" },
    { "America/Whitehorse", "Canada/Yukon" },
    { "America/Winnipeg", "Canada/Central" },
    { "Antarctica/McMurdo", "Antarctica/South_Pole" },
    { "Asia/Ashgabat", "Asia/Ashkhabad" },
    { "Asia/Calcutta", "IST" },
    { "Asia/Chongqing", "Asia/Chungking" },
    { "Asia/Dacca", "Asia/Dhaka", "BST" },
    { "Asia/Hong_Kong", "Hongkong" },
    { "Asia/Jerusalem", "Asia/Tel_Aviv", "Israel" },
    { "Asia/Karachi", "PLT" },
    { "Asia/Macao", "Asia/Macau" },
    { "Asia/Makassar", "Asia/Ujung_Pandang" },
    { "Asia/Nicosia", "Europe/Nicosia" },
    { "Asia/Riyadh87", "Mideast/Riyadh87" },
    { "Asia/Riyadh88", "Mideast/Riyadh88" },
    { "Asia/Riyadh89", "Mideast/Riyadh89" },
    { "Asia/Saigon", "VST" },
    { "Asia/Seoul", "ROK" },
    { "Asia/Shanghai", "CTT", "PRC" },
    { "Asia/Singapore", "Singapore" },
    { "Asia/Taipei", "ROC" },
    { "Asia/Tehran", "Iran" },
    { "Asia/Thimbu", "Asia/Thimphu" },
    { "Asia/Tokyo", "JST", "Japan" },
    { "Asia/Ulaanbaatar", "Asia/Ulan_Bator" },
    { "Asia/Yerevan", "NET" },
    { "Atlantic/Reykjavik", "Iceland" },
    { "Australia/Adelaide", "Australia/South" },
    { "Australia/Brisbane", "Australia/Queensland" },
    { "Australia/Broken_Hill", "Australia/Yancowinna" },
    { "ACT", "Australia/Darwin", "Australia/North" },
    { "Australia/Hobart", "Australia/Tasmania" },
    { "Australia/LHI", "Australia/Lord_Howe" },
    { "Australia/Melbourne", "Australia/Victoria" },
    { "Australia/Perth", "Australia/West" },
    { "AET", "Australia/ACT", "Australia/Canberra", "Australia/NSW", "Australia/Sydney" },
    { "Etc/GMT", "Etc/GMT+0", "Etc/GMT-0", "Etc/GMT0", "Etc/Greenwich", "GMT", "GMT+0", "GMT-0", "GMT0", "Greenwich" },
    { "Etc/UCT", "UCT" },
    { "Etc/UTC", "Etc/Universal", "Etc/Zulu", "UTC", "Universal", "Zulu" },
    { "Europe/Belgrade", "Europe/Ljubljana", "Europe/Sarajevo", "Europe/Skopje", "Europe/Zagreb" },
    { "Europe/Chisinau", "Europe/Tiraspol" },
    { "Eire", "Europe/Dublin" },
    { "Europe/Helsinki", "Europe/Mariehamn" },
    { "Asia/Istanbul", "Europe/Istanbul", "Turkey" },
    { "Europe/Lisbon", "Portugal" },
    { "Europe/London", "GB", "GB-Eire" },
    { "Europe/Moscow", "W-SU" },
    { "Arctic/Longyearbyen", "Atlantic/Jan_Mayen", "Europe/Oslo" },
    { "ECT", "Europe/Paris" },
    { "Europe/Bratislava", "Europe/Prague" },
    { "Europe/Rome", "Europe/San_Marino", "Europe/Vatican" },
    { "Europe/Warsaw", "Poland" },
    { "MIT", "Pacific/Apia" },
    { "NST", "NZ", "Pacific/Auckland" },
    { "NZ-CHAT", "Pacific/Chatham" },
    { "Chile/EasterIsland", "Pacific/Easter" },
    { "Pacific/Gambier", "SystemV/YST9" },
    { "Pacific/Guadalcanal", "SST" },
    { "HST", "Pacific/Honolulu", "SystemV/HST10", "US/Hawaii" },
    { "Kwajalein", "Pacific/Kwajalein" },
    { "Pacific/Pago_Pago", "Pacific/Samoa", "US/Samoa" },
    { "Pacific/Pitcairn", "SystemV/PST8" }
  };
  public static final String[][] COUNTRY = {
    { "", "Asia/Riyadh87", "Asia/Riyadh88", "Asia/Riyadh89", "CET", "EET", "Etc/GMT", "Etc/GMT+0", "Etc/GMT+1", "Etc/GMT+10", "Etc/GMT+11", "Etc/GMT+12", "Etc/GMT+2", "Etc/GMT+3", "Etc/GMT+4", "Etc/GMT+5", "Etc/GMT+6", "Etc/GMT+7", "Etc/GMT+8", "Etc/GMT+9", "Etc/GMT-0", "Etc/GMT-1", "Etc/GMT-10", "Etc/GMT-11", "Etc/GMT-12", "Etc/GMT-13", "Etc/GMT-14", "Etc/GMT-2", "Etc/GMT-3", "Etc/GMT-4", "Etc/GMT-5", "Etc/GMT-6", "Etc/GMT-7", "Etc/GMT-8", "Etc/GMT-9", "Etc/GMT0", "Etc/Greenwich", "Etc/UCT", "Etc/UTC", "Etc/Universal", "Etc/Zulu", "Factory", "GMT", "GMT+0", "GMT-0", "GMT0", "Greenwich", "MET", "Mideast/Riyadh87", "Mideast/Riyadh88", "Mideast/Riyadh89", "UCT", "UTC", "Universal", "WET", "Zulu" },
    { "AD", "Europe/Andorra" },
    { "AE", "Asia/Dubai" },
    { "AF", "Asia/Kabul" },
    { "AG", "America/Antigua" },
    { "AI", "America/Anguilla" },
    { "AL", "Europe/Tirane" },
    { "AM", "Asia/Yerevan", "NET" },
    { "AN", "America/Curacao" },
    { "AO", "Africa/Luanda" },
    { "AQ", "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/South_Pole", "Antarctica/Syowa", "Antarctica/Vostok" },
    { "AR", "AGT", "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/ComodRivadavia", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/San_Juan", "America/Argentina/Tucuman", "America/Argentina/Ushuaia", "America/Buenos_Aires", "America/Catamarca", "America/Cordoba", "America/Jujuy", "America/Mendoza", "America/Rosario" },
    { "AS", "Pacific/Pago_Pago", "Pacific/Samoa", "US/Samoa" },
    { "AT", "Europe/Vienna" },
    { "AU", "ACT", "AET", "Australia/ACT", "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Canberra", "Australia/Darwin", "Australia/Hobart", "Australia/LHI", "Australia/Lindeman", "Australia/Lord_Howe", "Australia/Melbourne", "Australia/NSW", "Australia/North", "Australia/Perth", "Australia/Queensland", "Australia/South", "Australia/Sydney", "Australia/Tasmania", "Australia/Victoria", "Australia/West", "Australia/Yancowinna" },
    { "AW", "America/Aruba" },
    { "AX", "Europe/Mariehamn" },
    { "AZ", "Asia/Baku" },
    { "BA", "Europe/Sarajevo" },
    { "BB", "America/Barbados" },
    { "BD", "Asia/Dacca", "Asia/Dhaka", "BST" },
    { "BE", "Europe/Brussels" },
    { "BF", "Africa/Ouagadougou" },
    { "BG", "Europe/Sofia" },
    { "BH", "Asia/Bahrain" },
    { "BI", "Africa/Bujumbura" },
    { "BJ", "Africa/Porto-Novo" },
    { "BM", "Atlantic/Bermuda" },
    { "BN", "Asia/Brunei" },
    { "BO", "America/La_Paz" },
    { "BR", "America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista", "America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza", "America/Maceio", "America/Manaus", "America/Noronha", "America/Porto_Acre", "America/Porto_Velho", "America/Recife", "America/Rio_Branco", "America/Sao_Paulo", "BET", "Brazil/Acre", "Brazil/DeNoronha", "Brazil/East", "Brazil/West" },
    { "BS", "America/Nassau" },
    { "BT", "Asia/Thimbu", "Asia/Thimphu" },
    { "BW", "Africa/Gaborone" },
    { "BY", "Europe/Minsk" },
    { "BZ", "America/Belize" },
    { "CA", "America/Cambridge_Bay", "America/Dawson", "America/Dawson_Creek", "America/Edmonton", "America/Glace_Bay", "America/Goose_Bay", "America/Halifax", "America/Inuvik", "America/Iqaluit", "America/Montreal", "America/Nipigon", "America/Pangnirtung", "America/Rainy_River", "America/Rankin_Inlet", "America/Regina", "America/St_Johns", "America/Swift_Current", "America/Thunder_Bay", "America/Toronto", "America/Vancouver", "America/Whitehorse", "America/Winnipeg", "America/Yellowknife", "CNT", "Canada/Atlantic", "Canada/Central", "Canada/East-Saskatchewan", "Canada/Eastern", "Canada/Mountain", "Canada/Newfoundland", "Canada/Pacific", "Canada/Saskatchewan", "Canada/Yukon", "SystemV/AST4ADT", "SystemV/CST6" },
    { "CC", "Indian/Cocos" },
    { "CD", "Africa/Kinshasa", "Africa/Lubumbashi" },
    { "CF", "Africa/Bangui" },
    { "CG", "Africa/Brazzaville" },
    { "CH", "Europe/Zurich" },
    { "CI", "Africa/Abidjan" },
    { "CK", "Pacific/Rarotonga" },
    { "CL", "America/Santiago", "Chile/Continental", "Chile/EasterIsland", "Pacific/Easter" },
    { "CM", "Africa/Douala" },
    { "CN", "Asia/Chongqing", "Asia/Chungking", "Asia/Harbin", "Asia/Kashgar", "Asia/Shanghai", "Asia/Urumqi", "CTT", "PRC" },
    { "CO", "America/Bogota" },
    { "CR", "America/Costa_Rica" },
    { "CS", "Europe/Belgrade" },
    { "CU", "America/Havana", "Cuba" },
    { "CV", "Atlantic/Cape_Verde" },
    { "CX", "Indian/Christmas" },
    { "CY", "Asia/Nicosia", "Europe/Nicosia" },
    { "CZ", "Europe/Prague" },
    { "DE", "Europe/Berlin" },
    { "DJ", "Africa/Djibouti" },
    { "DK", "Europe/Copenhagen" },
    { "DM", "America/Dominica" },
    { "DO", "America/Santo_Domingo" },
    { "DZ", "Africa/Algiers" },
    { "EC", "America/Guayaquil", "Pacific/Galapagos" },
    { "EE", "Europe/Tallinn" },
    { "EG", "ART", "Africa/Cairo", "Egypt" },
    { "EH", "Africa/El_Aaiun" },
    { "ER", "Africa/Asmera" },
    { "ES", "Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid" },
    { "ET", "Africa/Addis_Ababa", "EAT" },
    { "FI", "Europe/Helsinki" },
    { "FJ", "Pacific/Fiji" },
    { "FK", "Atlantic/Stanley" },
    { "FM", "Pacific/Kosrae", "Pacific/Ponape", "Pacific/Truk", "Pacific/Yap" },
    { "FO", "Atlantic/Faeroe" },
    { "FR", "ECT", "Europe/Paris" },
    { "GA", "Africa/Libreville" },
    { "GB", "Europe/Belfast", "Europe/London", "GB", "GB-Eire" },
    { "GD", "America/Grenada" },
    { "GE", "Asia/Tbilisi" },
    { "GF", "America/Cayenne" },
    { "GH", "Africa/Accra" },
    { "GI", "Europe/Gibraltar" },
    { "GL", "America/Danmarkshavn", "America/Godthab", "America/Scoresbysund", "America/Thule" },
    { "GM", "Africa/Banjul" },
    { "GN", "Africa/Conakry" },
    { "GP", "America/Guadeloupe" },
    { "GQ", "Africa/Malabo" },
    { "GR", "Europe/Athens" },
    { "GS", "Atlantic/South_Georgia" },
    { "GT", "America/Guatemala" },
    { "GU", "Pacific/Guam" },
    { "GW", "Africa/Bissau" },
    { "GY", "America/Guyana" },
    { "HK", "Asia/Hong_Kong", "Hongkong" },
    { "HN", "America/Tegucigalpa" },
    { "HR", "Europe/Zagreb" },
    { "HT", "America/Port-au-Prince" },
    { "HU", "Europe/Budapest" },
    { "ID", "Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak", "Asia/Ujung_Pandang" },
    { "IE", "Eire", "Europe/Dublin" },
    { "IL", "Asia/Jerusalem", "Asia/Tel_Aviv", "Israel" },
    { "IN", "Asia/Calcutta", "IST" },
    { "IO", "Indian/Chagos" },
    { "IQ", "Asia/Baghdad" },
    { "IR", "Asia/Tehran", "Iran" },
    { "IS", "Atlantic/Reykjavik", "Iceland" },
    { "IT", "Europe/Rome" },
    { "JM", "America/Jamaica", "Jamaica" },
    { "JO", "Asia/Amman" },
    { "JP", "Asia/Tokyo", "JST", "Japan" },
    { "KE", "Africa/Nairobi" },
    { "KG", "Asia/Bishkek" },
    { "KH", "Asia/Phnom_Penh" },
    { "KI", "Pacific/Enderbury", "Pacific/Kiritimati", "Pacific/Tarawa" },
    { "KM", "Indian/Comoro" },
    { "KN", "America/St_Kitts" },
    { "KP", "Asia/Pyongyang" },
    { "KR", "Asia/Seoul", "ROK" },
    { "KW", "Asia/Kuwait" },
    { "KY", "America/Cayman" },
    { "KZ", "Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Oral", "Asia/Qyzylorda" },
    { "LA", "Asia/Vientiane" },
    { "LB", "Asia/Beirut" },
    { "LC", "America/St_Lucia" },
    { "LI", "Europe/Vaduz" },
    { "LK", "Asia/Colombo" },
    { "LR", "Africa/Monrovia" },
    { "LS", "Africa/Maseru" },
    { "LT", "Europe/Vilnius" },
    { "LU", "Europe/Luxembourg" },
    { "LV", "Europe/Riga" },
    { "LY", "Africa/Tripoli", "Libya" },
    { "MA", "Africa/Casablanca" },
    { "MC", "Europe/Monaco" },
    { "MD", "Europe/Chisinau", "Europe/Tiraspol" },
    { "MG", "Indian/Antananarivo" },
    { "MH", "Kwajalein", "Pacific/Kwajalein", "Pacific/Majuro" },
    { "MK", "Europe/Skopje" },
    { "ML", "Africa/Bamako", "Africa/Timbuktu" },
    { "MM", "Asia/Rangoon" },
    { "MN", "Asia/Choibalsan", "Asia/Hovd", "Asia/Ulaanbaatar", "Asia/Ulan_Bator" },
    { "MO", "Asia/Macao", "Asia/Macau" },
    { "MP", "Pacific/Saipan" },
    { "MQ", "America/Martinique" },
    { "MR", "Africa/Nouakchott" },
    { "MS", "America/Montserrat" },
    { "MT", "Europe/Malta" },
    { "MU", "Indian/Mauritius" },
    { "MV", "Indian/Maldives" },
    { "MW", "Africa/Blantyre" },
    { "MX", "America/Cancun", "America/Chihuahua", "America/Ensenada", "America/Hermosillo", "America/Mazatlan", "America/Merida", "America/Mexico_City", "America/Monterrey", "America/Tijuana", "Mexico/BajaNorte", "Mexico/BajaSur", "Mexico/General" },
    { "MY", "Asia/Kuala_Lumpur", "Asia/Kuching" },
    { "MZ", "Africa/Maputo" },
    { "NA", "Africa/Windhoek" },
    { "NC", "Pacific/Noumea" },
    { "NE", "Africa/Niamey" },
    { "NF", "Pacific/Norfolk" },
    { "NG", "Africa/Lagos" },
    { "NI", "America/Managua" },
    { "NL", "Europe/Amsterdam" },
    { "NO", "Europe/Oslo" },
    { "NP", "Asia/Katmandu" },
    { "NR", "Pacific/Nauru" },
    { "NU", "Pacific/Niue" },
    { "NZ", "NST", "NZ", "NZ-CHAT", "Pacific/Auckland", "Pacific/Chatham" },
    { "OM", "Asia/Muscat" },
    { "PA", "America/Panama" },
    { "PE", "America/Lima" },
    { "PF", "Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti", "SystemV/YST9" },
    { "PG", "Pacific/Port_Moresby" },
    { "PH", "Asia/Manila" },
    { "PK", "Asia/Karachi", "PLT" },
    { "PL", "Europe/Warsaw", "Poland" },
    { "PM", "America/Miquelon" },
    { "PN", "Pacific/Pitcairn", "SystemV/PST8" },
    { "PR", "America/Puerto_Rico", "PRT", "SystemV/AST4" },
    { "PS", "Asia/Gaza" },
    { "PT", "Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon", "Portugal" },
    { "PW", "Pacific/Palau" },
    { "PY", "America/Asuncion" },
    { "QA", "Asia/Qatar" },
    { "RE", "Indian/Reunion" },
    { "RO", "Europe/Bucharest" },
    { "RU", "Asia/Anadyr", "Asia/Irkutsk", "Asia/Kamchatka", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg", "Europe/Kaliningrad", "Europe/Moscow", "Europe/Samara", "W-SU" },
    { "RW", "Africa/Kigali" },
    { "SA", "Asia/Riyadh" },
    { "SB", "Pacific/Guadalcanal", "SST" },
    { "SC", "Indian/Mahe" },
    { "SD", "Africa/Khartoum" },
    { "SE", "Europe/Stockholm" },
    { "SG", "Asia/Singapore", "Singapore" },
    { "SH", "Atlantic/St_Helena" },
    { "SI", "Europe/Ljubljana" },
    { "SJ", "Arctic/Longyearbyen", "Atlantic/Jan_Mayen" },
    { "SK", "Europe/Bratislava" },
    { "SL", "Africa/Freetown" },
    { "SM", "Europe/San_Marino" },
    { "SN", "Africa/Dakar" },
    { "SO", "Africa/Mogadishu" },
    { "SR", "America/Paramaribo" },
    { "ST", "Africa/Sao_Tome" },
    { "SV", "America/El_Salvador" },
    { "SY", "Asia/Damascus" },
    { "SZ", "Africa/Mbabane" },
    { "TC", "America/Grand_Turk" },
    { "TD", "Africa/Ndjamena" },
    { "TF", "Indian/Kerguelen" },
    { "TG", "Africa/Lome" },
    { "TH", "Asia/Bangkok" },
    { "TJ", "Asia/Dushanbe" },
    { "TK", "Pacific/Fakaofo" },
    { "TL", "Asia/Dili" },
    { "TM", "Asia/Ashgabat", "Asia/Ashkhabad" },
    { "TN", "Africa/Tunis" },
    { "TO", "Pacific/Tongatapu" },
    { "TR", "Asia/Istanbul", "Europe/Istanbul", "Turkey" },
    { "TT", "America/Port_of_Spain" },
    { "TV", "Pacific/Funafuti" },
    { "TW", "Asia/Taipei", "ROC" },
    { "TZ", "Africa/Dar_es_Salaam" },
    { "UA", "Europe/Kiev", "Europe/Simferopol", "Europe/Uzhgorod", "Europe/Zaporozhye" },
    { "UG", "Africa/Kampala" },
    { "UM", "Pacific/Johnston", "Pacific/Midway", "Pacific/Wake" },
    { "US", "AST", "America/Adak", "America/Anchorage", "America/Atka", "America/Boise", "America/Chicago", "America/Denver", "America/Detroit", "America/Fort_Wayne", "America/Indiana/Indianapolis", "America/Indiana/Knox", "America/Indiana/Marengo", "America/Indiana/Vevay", "America/Indianapolis", "America/Juneau", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Knox_IN", "America/Los_Angeles", "America/Louisville", "America/Menominee", "America/New_York", "America/Nome", "America/North_Dakota/Center", "America/Phoenix", "America/Shiprock", "America/Yakutat", "CST", "CST6CDT", "EST", "EST5EDT", "HST", "IET", "MST", "MST7MDT", "Navajo", "PNT", "PST", "PST8PDT", "Pacific/Honolulu", "SystemV/CST6CDT", "SystemV/EST5", "SystemV/EST5EDT", "SystemV/HST10", "SystemV/MST7", "SystemV/MST7MDT", "SystemV/PST8PDT", "SystemV/YST9YDT", "US/Alaska", "US/Aleutian", "US/Arizona", "US/Central", "US/East-Indiana", "US/Eastern", "US/Hawaii", "US/Indiana-Starke", "US/Michigan", "US/Mountain", "US/Pacific", "US/Pacific-New" },
    { "UY", "America/Montevideo" },
    { "UZ", "Asia/Samarkand", "Asia/Tashkent" },
    { "VA", "Europe/Vatican" },
    { "VC", "America/St_Vincent" },
    { "VE", "America/Caracas" },
    { "VG", "America/Tortola" },
    { "VI", "America/St_Thomas", "America/Virgin" },
    { "VN", "Asia/Saigon", "VST" },
    { "VU", "Pacific/Efate" },
    { "WF", "Pacific/Wallis" },
    { "WS", "MIT", "Pacific/Apia" },
    { "YE", "Asia/Aden" },
    { "YT", "Indian/Mayotte" },
    { "ZA", "Africa/Johannesburg" },
    { "ZM", "Africa/Lusaka" },
    { "ZW", "Africa/Harare", "CAT" }
  };
}
