#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.3 $ $Date: 2000/02/26 22:01:20 $
#

TOPDIR=	../../../..
PACKAGE=	com.ibm.test

include $(TOPDIR)/src/build/defs.gmk

SUBDIRS=	rbnf normalizer RuleBasedBreakIterator compression bnf translit search topleveltest

FILES_java=	$(TARGDIR)/TestFmwk.java			\

include $(TOPDIR)/src/build/rules.gmk
