#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.4 $ $Date: 2000/03/01 17:31:30 $
#

TOPDIR=	../../../..
PACKAGE=	com.ibm.test

include $(TOPDIR)/src/build/defs.gmk

SUBDIRS=	rbnf normalizer RuleBasedBreakIterator compression bnf translit search calendar topleveltest

FILES_java=	$(TARGDIR)/TestFmwk.java			\

include $(TOPDIR)/src/build/rules.gmk
