#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/25 18:21:59 $
#

TOPDIR=	../../../..
PACKAGE=	com.ibm.test

include $(TOPDIR)/src/build/defs.gmk

SUBDIRS=	rbnf normalizer RuleBasedBreakIterator compression bnf translit topleveltest

FILES_java=	$(TARGDIR)/TestFmwk.java			\

include $(TOPDIR)/src/build/rules.gmk
