#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:46 $
#

TOPDIR=	../../../..
PACKAGE=	com.ibm.test

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS=	rbnf normalizer RuleBasedBreakIterator compression bnf translit

FILES_java=	$(TARGDIR)/TestFmwk.java			\

!include $(TOPDIR)/src/build/rules.mak
