#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.2 $ $Date: 2000/02/28 04:04:49 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.RuleBasedBreakIterator

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/BreakIteratorTest.java   \
			$(TARGDIR)/SimpleBITest.java	\
			$(TARGDIR)/BreakIteratorRules_en_US_TEST.java

FILES_dict= $(TARGDIR)/english.dict \

include $(TOPDIR)/src/build/rules.gmk
