#
# @(#)$RCSfile: makefile,v $ $Revision: 1.3 $ $Date: 2000/03/02 00:37:58 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.rbbi

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/BreakIteratorTest.java   \
			$(TARGDIR)/SimpleBITest.java	\
			$(TARGDIR)/BreakIteratorRules_en_US_TEST.java

FILES_dict= $(TARGDIR)/english.dict \

!include $(TOPDIR)/src/build/rules.mak
