#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:48 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.RuleBasedBreakIterator

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/BreakIteratorTest.java   \
			$(TARGDIR)/SimpleBITest.java	\


!include $(TOPDIR)/src/build/rules.mak
