#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.3 $ $Date: 2000/03/02 00:39:03 $
#

TOPDIR=		../../../..
PACKAGE=	com.ibm.demo

include $(TOPDIR)/src/build/defs.gmk

SUBDIRS=	calendar holiday rbnf rbbi translit

FILES_java=	$(TARGDIR)/DemoApplet.java			\
			$(TARGDIR)/DemoUtility.java				\
			$(TARGDIR)/DemoTextBox.java				\


include $(TOPDIR)/src/build/rules.gmk
