#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:38 $
#

TOPDIR=		../../../..
PACKAGE=	com.ibm.demo

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS=	calendar holiday rbnf RuleBasedBreakIterator

FILES_java=	$(TARGDIR)/DemoApplet.java			\
			$(TARGDIR)/DemoUtility.java				\
			$(TARGDIR)/DemoTextBox.java				\


!include $(TOPDIR)/src/build/rules.mak
