#
# @(#)$RCSfile: makefile,v $ $Revision: 1.2 $ $Date: 2000/02/23 22:54:42 $
#

TOPDIR=		../../../..
PACKAGE=	com.ibm.demo

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS=	calendar holiday rbnf RuleBasedBreakIterator translit

FILES_java=	$(TARGDIR)/DemoApplet.java			\
			$(TARGDIR)/DemoUtility.java				\
			$(TARGDIR)/DemoTextBox.java				\


!include $(TOPDIR)/src/build/rules.mak
