#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:57 $
#

TOPDIR=		../../../..
PACKAGE=	com.ibm.text

!include $(TOPDIR)/src/build/defs.mak

SUBDIRS= resources components

FILES_java=	$(TARGDIR)/ChineseDateFormat.java	\
			$(TARGDIR)/ChineseDateSymbols.java	\
			$(TARGDIR)/DateFormatSymbols.java	\
			$(TARGDIR)/StringSearch.java		\
			$(TARGDIR)/SearchIterator.java		\
			$(TARGDIR)/SimpleDateFormat.java	\
												\
			$(TARGDIR)/NFRule.java				\
			$(TARGDIR)/NFRuleSet.java			\
			$(TARGDIR)/NFSubstitution.java		\
			                                    \
			$(TARGDIR)/UnicodeSet.java          \
			$(TARGDIR)/RuleBasedNumberFormat.java	\
												\
			$(TARGDIR)/ComposeData.java			\
			$(TARGDIR)/DecompData.java			\
			$(TARGDIR)/UInfo.java				\
			$(TARGDIR)/Normalizer.java			\
			$(TARGDIR)/ComposedCharIter.java	\
												\
			$(TARGDIR)/StringCharacterIterator.java	\
			$(TARGDIR)/CharSet.java				\
			$(TARGDIR)/BreakDictionary.java		\
			$(TARGDIR)/RuleBasedBreakIterator.java	\
			$(TARGDIR)/DictionaryBasedBreakIterator.java	\
			$(TARGDIR)/BreakIterator.java		\
			                                    \
			$(TARGDIR)/SCSU.java		        \
			$(TARGDIR)/UnicodeCompressor.java	\
			$(TARGDIR)/UnicodeDecompressor.java	\
			                                    \
			$(TARGDIR)/DigitList.java		    \
			$(TARGDIR)/DecimalFormatSymbols.java    \
			$(TARGDIR)/NumberFormat.java		\
			$(TARGDIR)/DecimalFormat.java       \
			                                    \
			$(TARGDIR)/CompoundTransliterator.java       \
			$(TARGDIR)/HangulJamoTransliterator.java       \
			$(TARGDIR)/HexToUnicodeTransliterator.java       \
			$(TARGDIR)/JamoHangulTransliterator.java       \
			$(TARGDIR)/NullTransliterator.java  \
			$(TARGDIR)/Replaceable.java         \
			$(TARGDIR)/ReplaceableString.java   \
			$(TARGDIR)/RuleBasedTransliterator.java       \
			$(TARGDIR)/SymbolTable.java       \
			$(TARGDIR)/TransliterationRule.java       \
			$(TARGDIR)/TransliterationRuleSet.java       \
			$(TARGDIR)/Transliterator.java       \
			$(TARGDIR)/UnicodeFilter.java       \
			$(TARGDIR)/UnicodeFilterLogic.java       \
			$(TARGDIR)/UnicodeToHexTransliterator.java       \
			
			                                    

!include $(TOPDIR)/src/build/rules.mak
