#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:40:05 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.tools.compression

!include $(TOPDIR)/src/build/defs.mak

FILES_java=	$(TARGDIR)/CompressionTableGenerator.java			\

!include $(TOPDIR)/src/build/rules.mak

