# Copyright (C) 2026 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html
#
# GitHub Action configuration script for ICU continuous integration tasks.

# Based on the documentation here:
#   https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows

name: Release - All ICU

on:
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run the tests.'
        type: boolean
        default: true
      deployToMaven:
        description: 'Deploy to Maven Central (using Sonatype OSSRH)'
        type: boolean
        default: false
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string

env:
  RELEASE_FOLDER: '${{ github.workspace }}/releaseDist'

permissions:
  contents: read

jobs:
  call-icu4c_msvcdistrelease:
    uses: ./.github/workflows/icu4c_msvcdistrelease.yml
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions: &all_permissions
      contents: write # So that we can upload to release
      id-token: write # For artifact attestation
      attestations: write # For artifact attestation
    with:
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
  call-release-icu4c-fedora:
    uses: ./.github/workflows/release-icu4c-fedora.yml
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions: *all_permissions
    with:
      runTests: ${{ inputs.runTests }}
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
  call-release-icu4c-ubuntu:
    uses: ./.github/workflows/release-icu4c-ubuntu.yml
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions: *all_permissions
    with:
      runTests: ${{ inputs.runTests }}
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
  call-release-icu4j-maven:
    uses: ./.github/workflows/release-icu4j-maven.yml # zizmor: ignore[excessive-permissions]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions: *all_permissions
    with:
      runTests: ${{ inputs.runTests }}
      deployToMaven: ${{ inputs.deployToMaven }}
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
  call-icu4x_icuexportdata:
    uses: ./.github/workflows/icu4x_icuexportdata.yml
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions: *all_permissions
    with:
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
  call-release-check-sign:
    needs: [ call-icu4c_msvcdistrelease, call-release-icu4c-fedora, call-release-icu4c-ubuntu, call-release-icu4j-maven, call-icu4x_icuexportdata ]
    uses: ./.github/workflows/release-check-sign.yml
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions:
      contents: write # So that we can upload to release
    with:
      gitReleaseTag: ${{ inputs.gitReleaseTag }}
