#
# @(#)$RCSfile: GNUmakefile,v $ $Revision: 1.1 $ $Date: 2000/03/01 18:32:30 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.test.calendar

include $(TOPDIR)/src/build/defs.gmk


FILES_java=	$(TARGDIR)/TestCase.java			\
			$(TARGDIR)/CalendarTest.java	\
			$(TARGDIR)/AstroTest.java	\
			$(TARGDIR)/HebrewTest.java	\
			$(TARGDIR)/IslamicTest.java	\



include $(TOPDIR)/src/build/rules.gmk
