#
# @(#)$RCSfile: makefile,v $ $Revision: 1.1 $ $Date: 2000/02/16 23:39:58 $
#

TOPDIR=		../../../../..
PACKAGE=	com.ibm.text.components

!include $(TOPDIR)/src/build/defs.mak


FILES_java=	$(TARGDIR)/DumbTextComponent.java	    \
			$(TARGDIR)/Selection.java	\

!include $(TOPDIR)/src/build/rules.mak
